import { useState } from "react";
const T={tr:{title:"Gümüş Fiyat Alarm Kurucusu",subtitle:"Hedef fiyat belirleyin, uyarı simülasyonu oluşturun",currentPrice:"Güncel Fiyat (simülasyon)",targetLabel:"Hedef Fiyat ($/ons)",dirLabel:"Yön",above:"Üstüne çıkarsa",below:"Altına düşerse",setAlert:"Alarm Kur",alerts:"Aktif Alarmlar",noAlerts:"Henüz alarm yok",triggered:"🔔 TETİKLENDİ!",waiting:"⏳ Bekliyor...",delete:"Sil",simNote:"Bu bir simülasyondur — gerçek fiyat bildirimi göndermez. Gerçek alarm için aracı kurum platformlarını kullanın.",sponsor:{text:"Gümüş yatırımınızı 925 ayar takılarla somutlaştırın.",cta:"İstanbul Gümüş"}},
en:{title:"Silver Price Alert Simulator",subtitle:"Set target prices and simulate price alerts",currentPrice:"Current Price (simulation)",targetLabel:"Target Price ($/oz)",dirLabel:"Direction",above:"Goes above",below:"Goes below",setAlert:"Set Alert",alerts:"Active Alerts",noAlerts:"No alerts set yet",triggered:"🔔 TRIGGERED!",waiting:"⏳ Waiting...",delete:"Delete",simNote:"This is a simulation — it does not send real price notifications. Use brokerage platforms for actual alerts.",sponsor:{text:"Make your silver investment tangible with 925 jewelry.",cta:"İstanbul Gümüş"}},
ar:{title:"محاكي تنبيه سعر الفضة",subtitle:"حدد أسعاراً مستهدفة وقم بمحاكاة التنبيهات",currentPrice:"السعر الحالي (محاكاة)",targetLabel:"السعر المستهدف ($/أونصة)",dirLabel:"الاتجاه",above:"يرتفع فوق",below:"ينخفض تحت",setAlert:"ضبط التنبيه",alerts:"التنبيهات النشطة",noAlerts:"لا توجد تنبيهات بعد",triggered:"🔔 تم التنبيه!",waiting:"⏳ انتظار...",delete:"حذف",simNote:"هذه محاكاة — لا ترسل إشعارات حقيقية.",sponsor:{text:"جسّد استثمارك في الفضة بمجوهرات ٩٢٥.",cta:"إسطنبول غوموش"}}
};
export default function PriceAlertTool(){
const[lang,setLang]=useState("tr");const[dark,setDark]=useState(true);const[price,setPrice]=useState(32.5);const[target,setTarget]=useState(35);const[dir,setDir]=useState("above");const[alerts,setAlerts]=useState([]);
const t=T[lang];const isRTL=lang==="ar";
const addAlert=()=>{setAlerts(prev=>[...prev,{id:Date.now(),target,dir,created:new Date().toLocaleTimeString()}])};
const removeAlert=(id)=>{setAlerts(prev=>prev.filter(a=>a.id!==id))};
const isTriggered=(a)=>a.dir==="above"?price>=a.target:price<=a.target;
const bgP=dark?"#0f0f14":"#FAFAF5";const textP=dark?"#e8e8ec":"#2C2C2C";const textS=dark?"#9a9aaa":"#6B7280";const accent=dark?"#C0C0C0":"#708090";const gold="#D4AF37";const border=dark?"rgba(192,192,192,0.1)":"rgba(0,0,0,0.06)";const bgCard=dark?"#1a1a24":"#ffffff";const fontD="'Playfair Display',Georgia,serif";const fontB=lang==="ar"?"'Noto Naskh Arabic',serif":"'Source Sans 3',sans-serif";
return(<div dir={isRTL?"rtl":"ltr"} style={{fontFamily:fontB,background:bgP,color:textP,minHeight:"100vh"}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;500;600&family=Noto+Naskh+Arabic:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');*{margin:0;padding:0;box-sizing:border-box}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}input[type=range]{width:100%;accent-color:#D4AF37}input[type=number]{padding:10px 14px;border-radius:8px;border:1px solid ${border};background:${bgP};color:${textP};font-size:16px;font-family:'JetBrains Mono',monospace;width:100%;outline:none}`}</style>
<nav style={{position:"sticky",top:0,zIndex:100,background:dark?"rgba(15,15,20,0.88)":"rgba(250,250,245,0.88)",backdropFilter:"blur(20px)",borderBottom:`1px solid ${border}`,padding:"0 24px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><span style={{fontFamily:fontD,fontWeight:600,fontSize:16}}>SilverAtlas</span></div><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{display:"flex",gap:2,background:dark?"rgba(255,255,255,0.05)":"rgba(0,0,0,0.04)",borderRadius:7,padding:2}}>{["tr","en","ar"].map(l=>(<button key={l} onClick={()=>setLang(l)} style={{border:"none",cursor:"pointer",padding:"3px 9px",borderRadius:5,fontSize:11,fontWeight:lang===l?600:400,background:lang===l?(dark?"rgba(192,192,192,0.15)":"rgba(0,0,0,0.08)"):"transparent",color:lang===l?textP:textS}}>{l==="ar"?"عر":l.toUpperCase()}</button>))}</div><button onClick={()=>setDark(!dark)} style={{border:"none",cursor:"pointer",background:"transparent",color:textS,fontSize:16,padding:4}}>{dark?"☀️":"🌙"}</button></div></nav>
<div style={{maxWidth:560,margin:"0 auto",padding:"40px 24px 80px",animation:"fadeUp 0.6s ease both"}}>
<h1 style={{fontFamily:fontD,fontSize:"clamp(24px,4vw,36px)",fontWeight:700,textAlign:"center",marginBottom:8}}>{t.title}</h1>
<p style={{textAlign:"center",color:textS,fontSize:14,marginBottom:32}}>{t.subtitle}</p>
<div style={{background:bgCard,borderRadius:16,padding:24,border:`1px solid ${border}`,marginBottom:16}}>
<div style={{fontSize:13,color:textS,marginBottom:6}}>{t.currentPrice}</div>
<div style={{fontSize:36,fontWeight:700,color:gold,fontFamily:"'JetBrains Mono',monospace",textAlign:"center",marginBottom:8}}>${price.toFixed(2)}</div>
<input type="range" min={15} max={60} step={0.1} value={price} onChange={e=>setPrice(+e.target.value)}/>
</div>
<div style={{background:bgCard,borderRadius:16,padding:24,border:`1px solid ${border}`,marginBottom:16}}>
<div style={{marginBottom:12}}><label style={{fontSize:13,color:textS,display:"block",marginBottom:6}}>{t.targetLabel}</label><input type="number" value={target} onChange={e=>setTarget(+e.target.value)} min={1} step={0.5}/></div>
<div style={{marginBottom:12}}><label style={{fontSize:13,color:textS,display:"block",marginBottom:6}}>{t.dirLabel}</label><div style={{display:"flex",gap:8}}>{["above","below"].map(d=>(<button key={d} onClick={()=>setDir(d)} style={{flex:1,padding:"10px",borderRadius:8,border:`1px solid ${dir===d?gold:border}`,background:dir===d?`${gold}22`:"transparent",color:dir===d?gold:textP,cursor:"pointer",fontSize:13,fontFamily:fontB}}>{d==="above"?t.above:t.below}</button>))}</div></div>
<button onClick={addAlert} style={{width:"100%",padding:"12px",borderRadius:8,border:"none",background:`linear-gradient(135deg,${gold},#c9a227)`,color:"#0f0f14",fontWeight:600,fontSize:14,cursor:"pointer",fontFamily:fontB}}>{t.setAlert}</button>
</div>
<div style={{background:bgCard,borderRadius:16,padding:24,border:`1px solid ${border}`,marginBottom:16}}>
<h3 style={{fontFamily:fontD,fontSize:16,fontWeight:600,color:accent,marginBottom:12}}>{t.alerts}</h3>
{alerts.length===0?<p style={{fontSize:13,color:textS}}>{t.noAlerts}</p>:alerts.map(a=>(<div key={a.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:`1px solid ${border}`}}>
<div><div style={{fontSize:14,fontWeight:600,color:isTriggered(a)?"#4CAF50":textP,fontFamily:"'JetBrains Mono',monospace"}}>${a.target} {a.dir==="above"?"↑":"↓"}</div><div style={{fontSize:11,color:textS}}>{a.created}</div></div>
<div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:12,color:isTriggered(a)?"#4CAF50":"#FF9800"}}>{isTriggered(a)?t.triggered:t.waiting}</span><button onClick={()=>removeAlert(a.id)} style={{border:"none",cursor:"pointer",background:"transparent",color:"#f44336",fontSize:11}}>{t.delete}</button></div>
</div>))}
</div>
<div style={{padding:12,background:dark?"rgba(255,152,0,0.06)":"rgba(255,152,0,0.08)",borderRadius:10,fontSize:12,color:textS,textAlign:"center",marginBottom:24,lineHeight:1.6}}>{t.simNote}</div>
<div style={{background:`linear-gradient(135deg,${dark?"rgba(212,175,55,0.06)":"rgba(212,175,55,0.08)"},transparent)`,borderRadius:14,padding:24,textAlign:"center",border:`1px solid ${gold}22`}}><p style={{fontSize:14,color:textS,marginBottom:12}}>{t.sponsor.text}</p><a href="https://instagram.com/istanbulgumustr" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"10px 28px",borderRadius:8,background:`linear-gradient(135deg,${gold},#c9a227)`,color:"#0f0f14",fontWeight:600,fontSize:14,textDecoration:"none"}}>{t.sponsor.cta}</a></div>
</div></div>);}
