import { useState } from "react";
const T={tr:{title:"Gümüş Saflık Test Rehberi",subtitle:"Evde uygulayabileceğiniz gümüş doğrulama yöntemleri",tests:[{name:"Mıknatıs Testi",icon:"🧲",difficulty:"Kolay",reliability:60,steps:["Güçlü bir neodimyum mıknatıs alın","Mıknatısı gümüş parçaya yaklaştırın","Gümüş manyetik DEĞİLDİR — çekiliyorsa gümüş değildir","Dikkat: Bazı sahte gümüşler de manyetik olmayabilir"],result:"Manyetik = kesinlikle gümüş değil. Manyetik değil = gümüş olabilir ama garanti değil."},{name:"Buz Testi",icon:"🧊",difficulty:"Kolay",reliability:70,steps:["Gümüş parçayı oda sıcaklığına getirin","Üzerine bir buz küpü koyun","Gümüş en iyi ısı iletkenidir — buz çok hızlı erimelidir","Normal metallerden belirgin şekilde hızlı erime gözlenmelidir"],result:"Çok hızlı erime = büyük olasılıkla gümüş. Normal erime = muhtemelen başka metal."},{name:"Ses Testi",icon:"🔔",difficulty:"Orta",reliability:65,steps:["Gümüş sikkeyi hafifçe bir metale vurun veya parmağınızla fırlatın","Gerçek gümüş uzun, berrak, çınlayan bir ses çıkarır","Sahte sikkeler kısa, tok ve donuk ses verir","Deneyim gerektirir — referans ses ile karşılaştırın"],result:"Uzun çınlama = muhtemelen gümüş. Kısa tok ses = muhtemelen sahte."},{name:"Asit Testi",icon:"⚗️",difficulty:"İleri",reliability:90,steps:["Gümüş test asidi (nitrik asit bazlı) ve mihenk taşı edinin","Parçayı mihenk taşına sürterek iz bırakın","İzin üzerine bir damla test asidi damlatın","Kremsi beyaz = 925; koyu gri = düşük saflık; yeşil = gümüş değil"],result:"En güvenilir evde test. Dikkat: Asit tehlikelidir, koruyucu ekipman kullanın."},{name:"Yoğunluk Testi",icon:"⚖️",difficulty:"Orta",reliability:85,steps:["Parçayı hassas terazide tartın (kuru ağırlık)","Su dolu ölçü kabına batırarak hacmini ölçün","Yoğunluk = kütle / hacim hesaplayın","Gümüş yoğunluğu: 10,49 g/cm³"],result:"10,49 ± 0,5 = muhtemelen gümüş. Büyük sapma = farklı metal."},{name:"XRF Analizi",icon:"🔬",difficulty:"Profesyonel",reliability:99,steps:["Kuyumcu veya test laboratuvarına gidin","XRF cihazı ile tahribatsız analiz yapılır","Sonuç: tam element bileşimi ve saflık yüzdesi","En kesin ve güvenilir yöntemdir"],result:"Kesin sonuç verir. Maliyeti 50-200₺ arasındadır."}],diffLabel:"Zorluk",relLabel:"Güvenilirlik",note:"Dikkat: Asit testi hariç hiçbir ev testi %100 kesin değildir. Şüphe durumunda profesyonel XRF analizi yaptırın.",sponsor:{text:"Damgalı, test edilmiş 925 ayar gümüş.",cta:"İstanbul Gümüş"}},
en:{title:"Silver Purity Test Guide",subtitle:"Home verification methods for testing silver authenticity",tests:[{name:"Magnet Test",icon:"🧲",difficulty:"Easy",reliability:60,steps:["Get a strong neodymium magnet","Bring the magnet close to the silver piece","Silver is NOT magnetic — if attracted, it's not silver","Note: Some fakes are also non-magnetic"],result:"Magnetic = definitely not silver. Non-magnetic = might be silver but not guaranteed."},{name:"Ice Test",icon:"🧊",difficulty:"Easy",reliability:70,steps:["Bring the silver piece to room temperature","Place an ice cube on it","Silver is the best thermal conductor — ice should melt very quickly","Noticeably faster melting than on other metals"],result:"Very fast melting = likely silver. Normal melting = probably another metal."},{name:"Ring Test",icon:"🔔",difficulty:"Medium",reliability:65,steps:["Gently tap the silver coin against metal or flick it","Real silver produces a long, clear, ringing tone","Fake coins produce a short, dull, flat sound","Requires experience — compare with reference"],result:"Long ring = likely silver. Short dull sound = likely fake."},{name:"Acid Test",icon:"⚗️",difficulty:"Advanced",reliability:90,steps:["Get silver test acid (nitric acid based) and a touchstone","Rub the piece on the touchstone to leave a streak","Apply a drop of test acid on the streak","Creamy white = 925; dark grey = low purity; green = not silver"],result:"Most reliable home test. Caution: acid is dangerous, use protective gear."},{name:"Density Test",icon:"⚖️",difficulty:"Medium",reliability:85,steps:["Weigh the piece on a precision scale (dry weight)","Submerge in a measuring cup of water to determine volume","Calculate density = mass / volume","Silver density: 10.49 g/cm³"],result:"10.49 ± 0.5 = likely silver. Large deviation = different metal."},{name:"XRF Analysis",icon:"🔬",difficulty:"Professional",reliability:99,steps:["Visit a jeweler or testing laboratory","XRF device performs non-destructive analysis","Result: full elemental composition and purity percentage","Most precise and reliable method"],result:"Gives definitive results. Cost: $5-20 typically."}],diffLabel:"Difficulty",relLabel:"Reliability",note:"Note: No home test except acid is 100% conclusive. When in doubt, get professional XRF analysis.",sponsor:{text:"Hallmarked, tested 925 sterling silver.",cta:"İstanbul Gümüş"}},
ar:{title:"دليل اختبار نقاء الفضة",subtitle:"طرق التحقق المنزلية لاختبار أصالة الفضة",tests:[{name:"اختبار المغناطيس",icon:"🧲",difficulty:"سهل",reliability:60,steps:["احصل على مغناطيس نيوديميوم قوي","قرّب المغناطيس من القطعة","الفضة ليست مغناطيسية"],result:"مغناطيسي = ليس فضة. غير مغناطيسي = قد يكون فضة."},{name:"اختبار الثلج",icon:"🧊",difficulty:"سهل",reliability:70,steps:["ضع مكعب ثلج على القطعة","الفضة أفضل موصل حراري — يجب أن يذوب الثلج بسرعة"],result:"ذوبان سريع جداً = على الأرجح فضة."},{name:"اختبار الحمض",icon:"⚗️",difficulty:"متقدم",reliability:90,steps:["استخدم حمض اختبار الفضة وحجر المحك","أبيض كريمي = ٩٢٥؛ أخضر = ليس فضة"],result:"الاختبار المنزلي الأكثر موثوقية."},{name:"تحليل XRF",icon:"🔬",difficulty:"احترافي",reliability:99,steps:["زر صائغاً أو مختبر اختبار","يعطي نتائج قاطعة"],result:"يعطي نتائج نهائية."}],diffLabel:"الصعوبة",relLabel:"الموثوقية",note:"ملاحظة: لا يوجد اختبار منزلي قاطع ١٠٠٪. استشر متخصصاً.",sponsor:{text:"فضة ٩٢٥ مختومة ومختبرة.",cta:"إسطنبول غوموش"}}
};
export default function PurityTestGuide(){
const[lang,setLang]=useState("tr");const[dark,setDark]=useState(true);const[expanded,setExpanded]=useState(0);const t=T[lang];const isRTL=lang==="ar";
const bgP=dark?"#0f0f14":"#FAFAF5";const textP=dark?"#e8e8ec":"#2C2C2C";const textS=dark?"#9a9aaa":"#6B7280";const accent=dark?"#C0C0C0":"#708090";const gold="#D4AF37";const border=dark?"rgba(192,192,192,0.1)":"rgba(0,0,0,0.06)";const bgCard=dark?"#1a1a24":"#ffffff";const fontD="'Playfair Display',Georgia,serif";const fontB=lang==="ar"?"'Noto Naskh Arabic',serif":"'Source Sans 3',sans-serif";
const relColor=(r)=>r>=90?"#4CAF50":r>=70?"#FF9800":"#f44336";
return(<div dir={isRTL?"rtl":"ltr"} style={{fontFamily:fontB,background:bgP,color:textP,minHeight:"100vh"}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;500;600&family=Noto+Naskh+Arabic:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');*{margin:0;padding:0;box-sizing:border-box}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}`}</style>
<nav style={{position:"sticky",top:0,zIndex:100,background:dark?"rgba(15,15,20,0.88)":"rgba(250,250,245,0.88)",backdropFilter:"blur(20px)",borderBottom:`1px solid ${border}`,padding:"0 24px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><span style={{fontFamily:fontD,fontWeight:600,fontSize:16}}>SilverAtlas</span></div><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{display:"flex",gap:2,background:dark?"rgba(255,255,255,0.05)":"rgba(0,0,0,0.04)",borderRadius:7,padding:2}}>{["tr","en","ar"].map(l=>(<button key={l} onClick={()=>setLang(l)} style={{border:"none",cursor:"pointer",padding:"3px 9px",borderRadius:5,fontSize:11,fontWeight:lang===l?600:400,fontFamily:l==="ar"?"'Noto Naskh Arabic',serif":fontB,background:lang===l?(dark?"rgba(192,192,192,0.15)":"rgba(0,0,0,0.08)"):"transparent",color:lang===l?textP:textS}}>{l==="ar"?"عر":l.toUpperCase()}</button>))}</div><button onClick={()=>setDark(!dark)} style={{border:"none",cursor:"pointer",background:"transparent",color:textS,fontSize:16,padding:4}}>{dark?"☀️":"🌙"}</button></div></nav>
<div style={{maxWidth:640,margin:"0 auto",padding:"40px 24px 80px",animation:"fadeUp 0.6s ease both"}}>
<h1 style={{fontFamily:fontD,fontSize:"clamp(24px,4vw,36px)",fontWeight:700,textAlign:"center",marginBottom:8}}>{t.title}</h1>
<p style={{textAlign:"center",color:textS,fontSize:14,marginBottom:32}}>{t.subtitle}</p>
{t.tests.map((test,i)=>(<div key={i} style={{background:bgCard,borderRadius:14,border:`1px solid ${expanded===i?gold+"44":border}`,marginBottom:12,overflow:"hidden",transition:"border-color 0.3s"}}>
<button onClick={()=>setExpanded(expanded===i?-1:i)} style={{width:"100%",padding:"16px 20px",border:"none",cursor:"pointer",background:"transparent",display:"flex",alignItems:"center",justifyContent:"space-between",fontFamily:fontB}}>
<div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:28}}>{test.icon}</span><div style={{textAlign:isRTL?"right":"left"}}><div style={{fontWeight:600,fontSize:15,color:textP}}>{test.name}</div><div style={{display:"flex",gap:8,marginTop:4,alignItems:"center"}}><span style={{fontSize:10,padding:"2px 6px",borderRadius:4,background:`${accent}15`,color:accent}}>{t.diffLabel}: {test.difficulty}</span><span style={{fontSize:10,padding:"2px 6px",borderRadius:4,background:`${relColor(test.reliability)}22`,color:relColor(test.reliability)}}>{t.relLabel}: {test.reliability}%</span></div></div></div>
<span style={{transform:expanded===i?"rotate(180deg)":"rotate(0deg)",transition:"transform 0.3s",color:textS}}>▼</span>
</button>
{expanded===i&&(<div style={{padding:"0 20px 20px"}}><div style={{marginBottom:12}}>{test.steps.map((s,j)=>(<div key={j} style={{display:"flex",gap:10,alignItems:"flex-start",marginBottom:8}}><span style={{fontSize:11,fontWeight:700,color:gold,minWidth:20}}>{j+1}.</span><span style={{fontSize:13,color:textP,lineHeight:1.6}}>{s}</span></div>))}</div><div style={{padding:12,background:dark?"rgba(212,175,55,0.06)":"rgba(212,175,55,0.08)",borderRadius:8,fontSize:13,color:textS,lineHeight:1.6,borderLeft:`3px solid ${gold}`}}>{test.result}</div></div>)}
</div>))}
<div style={{marginTop:16,padding:16,background:dark?"rgba(244,67,54,0.06)":"rgba(244,67,54,0.08)",borderRadius:10,fontSize:13,color:textS,lineHeight:1.6,textAlign:"center"}}>{t.note}</div>
<div style={{marginTop:24,background:`linear-gradient(135deg,${dark?"rgba(212,175,55,0.06)":"rgba(212,175,55,0.08)"},transparent)`,borderRadius:14,padding:24,textAlign:"center",border:`1px solid ${gold}22`}}><p style={{fontSize:14,color:textS,marginBottom:12}}>{t.sponsor.text}</p><a href="https://instagram.com/istanbulgumustr" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"10px 28px",borderRadius:8,background:`linear-gradient(135deg,${gold},#c9a227)`,color:"#0f0f14",fontWeight:600,fontSize:14,textDecoration:"none"}}>{t.sponsor.cta}</a></div>
</div></div>);}
