import { useState } from "react";
const T={tr:{title:"Gümüş vs Diğer Metaller",subtitle:"Gümüşü altın, platin, titanyum ve diğer metallerle karşılaştırın",selectLabel:"Metal Seçin (2-4 adet)",properties:"Özellikler",sponsor:{text:"925 ayar gümüşün farkını keşfedin.",cta:"İstanbul Gümüş"}},
en:{title:"Silver vs Other Metals",subtitle:"Compare silver with gold, platinum, titanium and other metals",selectLabel:"Select Metals (2-4)",properties:"Properties",sponsor:{text:"Discover the difference of 925 sterling silver.",cta:"İstanbul Gümüş"}},
ar:{title:"الفضة مقابل المعادن الأخرى",subtitle:"قارن الفضة بالذهب والبلاتين والتيتانيوم",selectLabel:"اختر المعادن (٢-٤)",properties:"الخصائص",sponsor:{text:"اكتشف فرق فضة ٩٢٥.",cta:"إسطنبول غوموش"}}
};
const METALS=[
{id:"silver",name:{tr:"Gümüş (925)",en:"Silver (925)",ar:"فضة (٩٢٥)"},symbol:"Ag",color:"#C0C0C0",density:10.49,melt:961,mohs:2.5,conductivity:429,price:1,hypoallergenic:true,tarnish:true},
{id:"gold",name:{tr:"Altın (18K)",en:"Gold (18K)",ar:"ذهب (١٨ قيراط)"},symbol:"Au",color:"#FFD700",density:15.6,melt:1064,mohs:2.75,conductivity:317,price:80,hypoallergenic:true,tarnish:false},
{id:"platinum",name:{tr:"Platin (950)",en:"Platinum (950)",ar:"بلاتين (٩٥٠)"},symbol:"Pt",color:"#E5E4E2",density:21.45,melt:1768,mohs:4,conductivity:71.6,price:90,hypoallergenic:true,tarnish:false},
{id:"titanium",name:{tr:"Titanyum",en:"Titanium",ar:"تيتانيوم"},symbol:"Ti",color:"#878681",density:4.51,melt:1668,mohs:6,conductivity:21.9,price:3,hypoallergenic:true,tarnish:false},
{id:"stainless",name:{tr:"Paslanmaz Çelik",en:"Stainless Steel",ar:"فولاذ مقاوم"},symbol:"Fe+",color:"#8B8D8E",density:7.93,melt:1510,mohs:5.5,conductivity:16.3,price:0.5,hypoallergenic:false,tarnish:false},
{id:"palladium",name:{tr:"Paladyum",en:"Palladium",ar:"بالاديوم"},symbol:"Pd",color:"#CED0CE",density:12.02,melt:1555,mohs:4.75,conductivity:71.8,price:35,hypoallergenic:true,tarnish:false},
];
export default function MetalComparator(){
const[lang,setLang]=useState("tr");const[dark,setDark]=useState(true);const[sel,setSel]=useState(["silver","gold"]);
const t=T[lang];const isRTL=lang==="ar";const toggle=(id)=>{setSel(prev=>prev.includes(id)?prev.filter(x=>x!==id).length>=2?prev.filter(x=>x!==id):prev:prev.length<4?[...prev,id]:prev)};
const bgP=dark?"#0f0f14":"#FAFAF5";const textP=dark?"#e8e8ec":"#2C2C2C";const textS=dark?"#9a9aaa":"#6B7280";const accent=dark?"#C0C0C0":"#708090";const gold2="#D4AF37";const border=dark?"rgba(192,192,192,0.1)":"rgba(0,0,0,0.06)";const bgCard=dark?"#1a1a24":"#ffffff";const fontD="'Playfair Display',Georgia,serif";const fontB=lang==="ar"?"'Noto Naskh Arabic',serif":"'Source Sans 3',sans-serif";
const selMetals=METALS.filter(m=>sel.includes(m.id));
const props=[{key:"density",label:{tr:"Yoğunluk (g/cm³)",en:"Density (g/cm³)",ar:"الكثافة"},max:22},{key:"melt",label:{tr:"Erime Noktası (°C)",en:"Melting Point (°C)",ar:"نقطة الانصهار"},max:1800},{key:"mohs",label:{tr:"Sertlik (Mohs)",en:"Hardness (Mohs)",ar:"الصلابة"},max:7},{key:"conductivity",label:{tr:"Isı İletkenliği (W/mK)",en:"Thermal Conductivity",ar:"التوصيل الحراري"},max:430},{key:"price",label:{tr:"Göreceli Fiyat",en:"Relative Price",ar:"السعر النسبي"},max:100}];
return(<div dir={isRTL?"rtl":"ltr"} style={{fontFamily:fontB,background:bgP,color:textP,minHeight:"100vh"}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;500;600&family=Noto+Naskh+Arabic:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');*{margin:0;padding:0;box-sizing:border-box}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}`}</style>
<nav style={{position:"sticky",top:0,zIndex:100,background:dark?"rgba(15,15,20,0.88)":"rgba(250,250,245,0.88)",backdropFilter:"blur(20px)",borderBottom:`1px solid ${border}`,padding:"0 24px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold2})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><span style={{fontFamily:fontD,fontWeight:600,fontSize:16}}>SilverAtlas</span></div><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{display:"flex",gap:2,background:dark?"rgba(255,255,255,0.05)":"rgba(0,0,0,0.04)",borderRadius:7,padding:2}}>{["tr","en","ar"].map(l=>(<button key={l} onClick={()=>setLang(l)} style={{border:"none",cursor:"pointer",padding:"3px 9px",borderRadius:5,fontSize:11,fontWeight:lang===l?600:400,background:lang===l?(dark?"rgba(192,192,192,0.15)":"rgba(0,0,0,0.08)"):"transparent",color:lang===l?textP:textS}}>{l==="ar"?"عر":l.toUpperCase()}</button>))}</div><button onClick={()=>setDark(!dark)} style={{border:"none",cursor:"pointer",background:"transparent",color:textS,fontSize:16,padding:4}}>{dark?"☀️":"🌙"}</button></div></nav>
<div style={{maxWidth:700,margin:"0 auto",padding:"40px 24px 80px",animation:"fadeUp 0.6s ease both"}}>
<h1 style={{fontFamily:fontD,fontSize:"clamp(24px,4vw,36px)",fontWeight:700,textAlign:"center",marginBottom:8}}>{t.title}</h1>
<p style={{textAlign:"center",color:textS,fontSize:14,marginBottom:24}}>{t.subtitle}</p>
<div style={{marginBottom:24}}><div style={{fontSize:13,color:textS,marginBottom:8}}>{t.selectLabel}</div><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{METALS.map(m=>{const isSel=sel.includes(m.id);return(<button key={m.id} onClick={()=>toggle(m.id)} style={{padding:"8px 14px",borderRadius:20,border:`1px solid ${isSel?m.color:border}`,background:isSel?m.color+"22":"transparent",color:isSel?m.color:textS,fontSize:12,cursor:"pointer",fontWeight:isSel?600:400,fontFamily:fontB,transition:"all 0.2s"}}>{m.symbol} {m.name[lang]}</button>)})}</div></div>
<div style={{background:bgCard,borderRadius:16,padding:24,border:`1px solid ${border}`}}>
<h3 style={{fontFamily:fontD,fontSize:18,fontWeight:600,color:accent,marginBottom:20}}>{t.properties}</h3>
{props.map(p=>(<div key={p.key} style={{marginBottom:20}}><div style={{fontSize:12,color:textS,marginBottom:8}}>{p.label[lang]}</div>{selMetals.map(m=>(<div key={m.id} style={{display:"flex",alignItems:"center",gap:10,marginBottom:6}}><span style={{fontSize:11,color:m.color,fontWeight:600,minWidth:32,fontFamily:"'JetBrains Mono',monospace"}}>{m.symbol}</span><div style={{flex:1,height:16,background:`${border}`,borderRadius:8,overflow:"hidden"}}><div style={{width:`${(m[p.key]/p.max)*100}%`,height:"100%",background:m.color,borderRadius:8,transition:"width 0.5s ease"}}></div></div><span style={{fontSize:12,color:textP,fontFamily:"'JetBrains Mono',monospace",minWidth:48,textAlign:"right"}}>{m[p.key]}</span></div>))}</div>))}
</div>
<div style={{marginTop:24,background:`linear-gradient(135deg,${dark?"rgba(212,175,55,0.06)":"rgba(212,175,55,0.08)"},transparent)`,borderRadius:14,padding:24,textAlign:"center",border:`1px solid ${gold2}22`}}><p style={{fontSize:14,color:textS,marginBottom:12}}>{t.sponsor.text}</p><a href="https://instagram.com/istanbulgumustr" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"10px 28px",borderRadius:8,background:`linear-gradient(135deg,${gold2},#c9a227)`,color:"#0f0f14",fontWeight:600,fontSize:14,textDecoration:"none"}}>{t.sponsor.cta}</a></div>
</div></div>);}
