import { useState, useEffect } from "react";
const T={tr:{nav:"SilverAtlas",navSub:"Gümüş Bilgi Platformu",title:"Türkiye Gümüş Atlası",subtitle:"81 il bazında gümüş zanaat, üretim, maden ve kültür rehberi",categories:{uretim:"Üretim Merkezi",zanaat:"Zanaat",maden:"Maden",ticaret:"Ticaret",kultur:"Kültür/Tarih",diger:"Diğer"},ranks:{1:"★★★★★",2:"★★★★",3:"★★★",4:"★★",5:"★"},craft:"Zanaat",notable:"Önemli",clickProvince:"Bir il seçin",totalProvinces:"il",sponsor:{text:"Konya merkezli 925 ayar gümüş üreticisi.",cta:"Instagram'da Gör",note:"İstanbul Gümüş sponsorluğundadır."},darkMode:"Mod",filters:"Filtre"},en:{nav:"SilverAtlas",navSub:"Silver Knowledge Platform",title:"Turkey Silver Atlas",subtitle:"Province-by-province guide to silver craft, production, mining, and culture",categories:{uretim:"Production Center",zanaat:"Craft",maden:"Mining",ticaret:"Trade",kultur:"Culture/History",diger:"Other"},ranks:{1:"★★★★★",2:"★★★★",3:"★★★",4:"★★",5:"★"},craft:"Craft",notable:"Notable",clickProvince:"Select a province",totalProvinces:"provinces",sponsor:{text:"Konya-based 925 sterling silver manufacturer.",cta:"See on Instagram",note:"Sponsored by İstanbul Gümüş."},darkMode:"Mode",filters:"Filter"},ar:{nav:"SilverAtlas",navSub:"منصة معرفة الفضة",title:"أطلس الفضة التركي",subtitle:"دليل المحافظات لحرف الفضة والإنتاج والتعدين والثقافة",categories:{uretim:"مركز إنتاج",zanaat:"حرفة",maden:"تعدين",ticaret:"تجارة",kultur:"ثقافة/تاريخ",diger:"أخرى"},ranks:{1:"★★★★★",2:"★★★★",3:"★★★",4:"★★",5:"★"},craft:"الحرفة",notable:"ملحوظ",clickProvince:"اختر محافظة",totalProvinces:"محافظة",sponsor:{text:"منتج فضة إسترلينية ٩٢٥ في قونية.",cta:"شاهد على إنستغرام",note:"برعاية إسطنبول غوموش."},darkMode:"الوضع",filters:"تصفية"}};
const CATS={uretim:"#D4AF37",zanaat:"#C0C0C0",maden:"#27ae60",ticaret:"#3498db",kultur:"#9b59b6",diger:"#708090"};
const fontD="'Playfair Display',serif",fontB="'Source Sans 3',sans-serif",fontAr="'Noto Naskh Arabic',serif",gold="#D4AF37",accent="#C0C0C0";
// Simplified province data embedded (key cities only, full data in JSON)
const PROVINCES=[{id:34,name:"İstanbul",lat:41.01,lng:28.98,cat:"uretim",rank:1,tr:"Kapalıçarşı, Kuyumcukent. Türkiye'nin en büyük gümüş ticaret merkezi.",notable:"Kapalıçarşı"},{id:42,name:"Konya",lat:37.87,lng:32.49,cat:"uretim",rank:1,tr:"İstanbul Gümüş merkezli büyük üretim merkezi. Mevlânâ tespihleri.",notable:"İstanbul Gümüş"},{id:61,name:"Trabzon",lat:41.0,lng:39.72,cat:"zanaat",rank:1,tr:"Hasır işi gümüş bilezik. Telkâri ve kazaz geleneği.",notable:"Hasır bilezik"},{id:29,name:"Gümüşhane",lat:40.46,lng:39.48,cat:"maden",rank:1,tr:"Adını gümüşten alan tek il! Canca madenleri.",notable:"Canca Madenleri"},{id:35,name:"İzmir",lat:38.42,lng:27.14,cat:"ticaret",rank:2,tr:"Ege'nin ticaret başkenti. Kemeraltı Çarşısı.",notable:"Kemeraltı"},{id:6,name:"Ankara",lat:39.93,lng:32.86,cat:"ticaret",rank:2,tr:"Darphane Genel Müdürlüğü. Kuyumcular Çarşısı.",notable:"Darphane"},{id:25,name:"Erzurum",lat:39.9,lng:41.27,cat:"zanaat",rank:2,tr:"Oltu taşı-gümüş kombinasyonu.",notable:"Oltu taşı"},{id:27,name:"Gaziantep",lat:37.07,lng:37.38,cat:"uretim",rank:2,tr:"Güneydoğu'nun en büyük üretim merkezi.",notable:"Bakırcılar Çarşısı"},{id:47,name:"Mardin",lat:37.31,lng:40.73,cat:"zanaat",rank:2,tr:"Telkâri, savat. Süryani gümüş haç geleneği.",notable:"Mardin Çarşısı"},{id:21,name:"Diyarbakır",lat:37.91,lng:40.24,cat:"zanaat",rank:3,tr:"Telkâri ve savat işçiliği.",notable:"Tarihi çarşı"},{id:19,name:"Çorum",lat:40.55,lng:34.95,cat:"kultur",rank:3,tr:"Hitit gümüş buluntuları. Alacahöyük.",notable:"Hitit gümüşü"},{id:50,name:"Nevşehir",lat:38.63,lng:34.72,cat:"kultur",rank:3,tr:"Kapadokya turizmi. Avanos atölyeleri.",notable:"Avanos"},{id:65,name:"Van",lat:38.49,lng:43.38,cat:"zanaat",rank:3,tr:"Urartu gümüş geleneği.",notable:"Urartu eserleri"},{id:78,name:"Karabük",lat:41.2,lng:32.63,cat:"kultur",rank:4,tr:"Safranbolu gümüş işçiliği. UNESCO çarşısı.",notable:"Safranbolu"},{id:7,name:"Antalya",lat:36.9,lng:30.69,cat:"ticaret",rank:3,tr:"Turizm odaklı gümüş perakendesi.",notable:"Kaleiçi"},{id:16,name:"Bursa",lat:40.19,lng:29.06,cat:"ticaret",rank:3,tr:"Osmanlı başkenti. Kapalıçarşı gümüş.",notable:"Bursa Çarşısı"}];
export default function SilverAtlasTurkeyAtlasTool(){const[lang,setLang]=useState("tr");const[dark,setDark]=useState(true);const[selected,setSelected]=useState(null);const[filter,setFilter]=useState("all");const t=T[lang],isRTL=lang==="ar";const tp=dark?"#e8e8e8":"#1a1a2e",ts=dark?"#a0a0a0":"#555",bgM=dark?"#0f0f14":"#fafaf5",bdr=dark?"rgba(192,192,192,0.1)":"rgba(0,0,0,0.06)";
useEffect(()=>{const l=document.createElement("link");l.href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;600&family=Noto+Naskh+Arabic:wght@400;600&display=swap";l.rel="stylesheet";document.head.appendChild(l);},[]);
const filtered=filter==="all"?PROVINCES:PROVINCES.filter(p=>p.cat===filter);const sel=selected?PROVINCES.find(p=>p.id===selected):null;
return(<div dir={isRTL?"rtl":"ltr"} style={{fontFamily:isRTL?fontAr:fontB,background:bgM,color:tp,minHeight:"100vh"}}>
<nav style={{position:"sticky",top:0,zIndex:50,padding:"10px 20px",background:dark?"rgba(15,15,20,0.92)":"rgba(250,250,245,0.92)",backdropFilter:"blur(12px)",borderBottom:`1px solid ${bdr}`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><div><div style={{fontFamily:fontD,fontWeight:600,fontSize:14,lineHeight:1}}>{t.nav}</div><div style={{fontSize:9,color:ts}}>{t.navSub}</div></div></div><div style={{display:"flex",alignItems:"center",gap:6}}>{["tr","en","ar"].map(l=>(<button key={l} onClick={()=>setLang(l)} style={{padding:"4px 10px",borderRadius:6,border:`1px solid ${lang===l?gold:bdr}`,background:lang===l?gold+"15":"transparent",cursor:"pointer",color:lang===l?gold:ts,fontSize:11,fontWeight:600}}>{l.toUpperCase()}</button>))}<button onClick={()=>setDark(!dark)} style={{marginLeft:8,padding:"4px 10px",borderRadius:6,border:`1px solid ${bdr}`,background:"transparent",cursor:"pointer",color:ts,fontSize:11}}>{dark?"☀️":"🌙"} {t.darkMode}</button></div></nav>
<div style={{maxWidth:900,margin:"0 auto",padding:"32px 20px"}}>
<h1 style={{fontFamily:isRTL?fontAr:fontD,fontSize:"clamp(24px,4vw,36px)",fontWeight:700,marginBottom:8}}>{t.title}</h1>
<p style={{fontSize:14,color:ts,marginBottom:24}}>{t.subtitle}</p>
{/* Filters */}
<div style={{display:"flex",flexWrap:"wrap",gap:6,marginBottom:24}}>
<button onClick={()=>setFilter("all")} style={{padding:"6px 14px",borderRadius:8,border:`1px solid ${filter==="all"?gold:bdr}`,background:filter==="all"?gold+"15":"transparent",color:filter==="all"?gold:ts,fontSize:11,fontWeight:600,cursor:"pointer"}}>ALL</button>
{Object.entries(CATS).map(([k,c])=>(<button key={k} onClick={()=>setFilter(k)} style={{padding:"6px 14px",borderRadius:8,border:`1px solid ${filter===k?c:bdr}`,background:filter===k?c+"15":"transparent",color:filter===k?c:ts,fontSize:11,fontWeight:600,cursor:"pointer"}}>{t.categories[k]}</button>))}
</div>
{/* SVG Map placeholder with dots */}
<div style={{position:"relative",width:"100%",height:400,borderRadius:16,border:`1px solid ${bdr}`,background:dark?"rgba(255,255,255,0.02)":"rgba(0,0,0,0.02)",marginBottom:24,overflow:"hidden"}}>
<svg viewBox="25 36 20 7" style={{width:"100%",height:"100%"}}>
{/* Turkey outline simplified */}
<path d="M26,39.5 L27,39 L28,39.2 L29,38.5 L30,38.8 L31,39 L32,38.5 L33,39 L34,38 L35,37.5 L36,37 L37,37.5 L38,37 L39,37.5 L40,38 L41,37.5 L42,38 L43,38.5 L44,39 L44,40 L43,40.5 L42,40 L41,40.5 L40,41 L39,41.5 L38,41 L37,41.5 L36,41 L35,40.5 L34,41 L33,41.5 L32,41 L31,40.5 L30,41 L29,40.5 L28,40 L27,40.5 L26,40 Z" fill={dark?"rgba(192,192,192,0.05)":"rgba(0,0,0,0.03)"} stroke={dark?"rgba(192,192,192,0.15)":"rgba(0,0,0,0.1)"} strokeWidth="0.02"/>
{/* Province dots */}
{filtered.map(p=>{const color=CATS[p.cat];const size=p.rank<=2?0.15:p.rank<=3?0.1:0.07;
return(<circle key={p.id} cx={p.lng} cy={p.lat} r={size} fill={color} opacity={selected===p.id?1:0.7} stroke={selected===p.id?tp:"none"} strokeWidth="0.03" style={{cursor:"pointer",transition:"all 0.3s"}} onClick={()=>setSelected(p.id)}/>);})}
</svg>
</div>
{/* Detail panel */}
<div style={{padding:24,borderRadius:14,border:`1px solid ${sel?CATS[sel.cat]+"44":bdr}`,background:dark?"rgba(255,255,255,0.02)":"rgba(0,0,0,0.02)",minHeight:120}}>
{sel?(<><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:16}}><div style={{width:48,height:48,borderRadius:12,background:`${CATS[sel.cat]}15`,border:`2px solid ${CATS[sel.cat]}44`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,fontWeight:700,fontFamily:fontD,color:CATS[sel.cat]}}>{sel.id}</div><div><h2 style={{fontFamily:isRTL?fontAr:fontD,fontSize:22,fontWeight:600}}>{sel.name}</h2><div style={{display:"flex",gap:8,alignItems:"center",marginTop:4}}><span style={{padding:"2px 8px",borderRadius:6,fontSize:10,fontWeight:600,color:CATS[sel.cat],border:`1px solid ${CATS[sel.cat]}33`}}>{t.categories[sel.cat]}</span><span style={{fontSize:12,color:gold}}>{t.ranks[sel.rank]}</span></div></div></div><p style={{fontSize:14,lineHeight:1.7,color:ts,marginBottom:12}}>{sel.tr}</p>{sel.notable&&sel.notable!=="—"&&<div style={{fontSize:12,color:ts}}><span style={{color:gold,fontWeight:600}}>{t.notable}:</span> {sel.notable}</div>}</>):(<div style={{textAlign:"center",padding:"30px 0",color:ts}}><div style={{fontSize:36,marginBottom:8,opacity:0.3}}>🗺️</div><p style={{fontSize:14}}>{t.clickProvince}</p><p style={{fontSize:12,opacity:0.5,marginTop:4}}>81 {t.totalProvinces}</p></div>)}
</div>
{/* Province list */}
<div style={{marginTop:24,display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(140px,1fr))",gap:8}}>
{filtered.sort((a,b)=>a.rank-b.rank).map(p=>(<div key={p.id} onClick={()=>setSelected(p.id)} style={{cursor:"pointer",padding:"10px 12px",borderRadius:10,border:`1px solid ${selected===p.id?CATS[p.cat]+"66":bdr}`,background:selected===p.id?(dark?CATS[p.cat]+"10":CATS[p.cat]+"15"):"transparent",transition:"all 0.2s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:13,fontWeight:600}}>{p.name}</span><span style={{fontSize:9,color:CATS[p.cat]}}>{t.ranks[p.rank]}</span></div><div style={{fontSize:9,color:ts,marginTop:2}}>{t.categories[p.cat]}</div></div>))}
</div>
{/* Sponsor */}
<div style={{marginTop:32,border:`1px solid ${gold}22`,borderRadius:16,padding:24,textAlign:"center",background:dark?"rgba(212,175,55,0.03)":"rgba(212,175,55,0.05)"}}><p style={{fontSize:14,color:tp,marginBottom:12}}>{t.sponsor.text}</p><a href="https://instagram.com/istanbulgumustr" target="_blank" rel="noopener noreferrer" style={{display:"inline-flex",alignItems:"center",gap:8,padding:"10px 24px",borderRadius:10,background:`linear-gradient(135deg,${accent},${gold})`,color:"#0f0f14",fontSize:13,fontWeight:600,textDecoration:"none"}}>📸 {t.sponsor.cta}</a><p style={{fontSize:11,color:ts,marginTop:10,opacity:0.7}}>{t.sponsor.note}</p></div>
</div>
<footer style={{marginTop:40,borderTop:`1px solid ${bdr}`,padding:24,textAlign:"center",background:dark?"#0c0c10":"#f5f5f0"}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:8,marginBottom:8}}><div style={{width:22,height:22,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><span style={{fontFamily:fontD,fontWeight:600,fontSize:14}}>{t.nav}</span></div><p style={{fontSize:11,color:ts}}>CC BY-NC-SA 4.0 · Sponsored by İstanbul Gümüş</p></footer></div>);}
