import { useState } from "react";
const ITEMS={tr:{categories:[{name:"Kolye",items:["İnce Zincir","Kalın Zincir","Choker","Pandora Kolye","Taşlı Kolye","Madalyon"]},{name:"Bileklik",items:["İnce Bangle","Kelepçe","Zincir Bileklik","Charm Bileklik","Cuff"]},{name:"Yüzük",items:["İnce Band","Statement","Taşlı Yüzük","Ayarlanabilir","Parmak Arası"]},{name:"Küpe",items:["Halka","Sallantılı","Stud","Ear Cuff","Damla"]}],title:"Takı Kombinasyon Oluşturucu",subtitle:"Gümüş takı stilinizi oluşturun",selected:"Seçilen Parçalar",empty:"Parça seçin...",tips:"Stil İpuçları",tipsText:["Maksimum 3-4 parça kombine edin — az çoktur","Bir odak noktası belirleyin: ya statement kolye ya da büyük küpeler","Farklı kalınlıklarda parçalar kontrast yaratır","Aynı ton gümüşte kalın — parlak ve mat karıştırmak riskli"],clear:"Temizle",sponsor:{text:"Kombinasyonunuz için 925 ayar gümüş parçalar.",cta:"İstanbul Gümüş"}},
en:{categories:[{name:"Necklace",items:["Fine Chain","Heavy Chain","Choker","Pendant","Gemstone Necklace","Locket"]},{name:"Bracelet",items:["Thin Bangle","Cuff","Chain Bracelet","Charm Bracelet","Wide Cuff"]},{name:"Ring",items:["Thin Band","Statement","Gemstone Ring","Adjustable","Midi Ring"]},{name:"Earring",items:["Hoop","Drop","Stud","Ear Cuff","Chandelier"]}],title:"Jewelry Combination Builder",subtitle:"Create your silver jewelry style",selected:"Selected Pieces",empty:"Select pieces...",tips:"Styling Tips",tipsText:["Combine max 3-4 pieces — less is more","Set one focal point: either statement necklace or bold earrings","Mix different thicknesses for contrast","Stay in the same silver tone — mixing polished and matte is risky"],clear:"Clear All",sponsor:{text:"925 silver pieces for your combination.",cta:"İstanbul Gümüş"}},
ar:{categories:[{name:"قلادة",items:["سلسلة رفيعة","سلسلة سميكة","تشوكر","قلادة معلقة","قلادة مرصعة","ميدالية"]},{name:"سوار",items:["بانجل رفيع","كاف","سوار سلسلة","سوار تعليقات","كاف عريض"]},{name:"خاتم",items:["حلقة رفيعة","ستيتمنت","خاتم مرصع","قابل للتعديل","ميدي"]},{name:"حلق",items:["حلقي","متدلي","ستاد","إير كاف","ثريا"]}],title:"منشئ تنسيق المجوهرات",subtitle:"أنشئ أسلوب مجوهراتك الفضية",selected:"القطع المختارة",empty:"اختر قطعاً...",tips:"نصائح التنسيق",tipsText:["ادمج ٣-٤ قطع كحد أقصى","حدد نقطة محورية واحدة","امزج سماكات مختلفة للتباين"],clear:"مسح الكل",sponsor:{text:"قطع فضة ٩٢٥ لتنسيقك.",cta:"إسطنبول غوموش"}}
};
const catIcons=["📿","💎","💍","✨"];
export default function JewelryCombinator(){
const[lang,setLang]=useState("tr");const[dark,setDark]=useState(true);const[selected,setSelected]=useState([]);
const t=ITEMS[lang];const isRTL=lang==="ar";
const toggle=(cat,item)=>{const key=cat+":"+item;setSelected(prev=>prev.includes(key)?prev.filter(x=>x!==key):[...prev,key])};
const bgP=dark?"#0f0f14":"#FAFAF5";const textP=dark?"#e8e8ec":"#2C2C2C";const textS=dark?"#9a9aaa":"#6B7280";const accent=dark?"#C0C0C0":"#708090";const gold="#D4AF37";const border=dark?"rgba(192,192,192,0.1)":"rgba(0,0,0,0.06)";const bgCard=dark?"#1a1a24":"#ffffff";const fontD="'Playfair Display',Georgia,serif";const fontB=lang==="ar"?"'Noto Naskh Arabic',serif":"'Source Sans 3',sans-serif";
return(<div dir={isRTL?"rtl":"ltr"} style={{fontFamily:fontB,background:bgP,color:textP,minHeight:"100vh"}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;500;600&family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap');*{margin:0;padding:0;box-sizing:border-box}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}`}</style>
<nav style={{position:"sticky",top:0,zIndex:100,background:dark?"rgba(15,15,20,0.88)":"rgba(250,250,245,0.88)",backdropFilter:"blur(20px)",borderBottom:`1px solid ${border}`,padding:"0 24px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><span style={{fontFamily:fontD,fontWeight:600,fontSize:16}}>SilverAtlas</span></div><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{display:"flex",gap:2,background:dark?"rgba(255,255,255,0.05)":"rgba(0,0,0,0.04)",borderRadius:7,padding:2}}>{["tr","en","ar"].map(l=>(<button key={l} onClick={()=>setLang(l)} style={{border:"none",cursor:"pointer",padding:"3px 9px",borderRadius:5,fontSize:11,fontWeight:lang===l?600:400,background:lang===l?(dark?"rgba(192,192,192,0.15)":"rgba(0,0,0,0.08)"):"transparent",color:lang===l?textP:textS}}>{l==="ar"?"عر":l.toUpperCase()}</button>))}</div><button onClick={()=>setDark(!dark)} style={{border:"none",cursor:"pointer",background:"transparent",color:textS,fontSize:16,padding:4}}>{dark?"☀️":"🌙"}</button></div></nav>
<div style={{maxWidth:640,margin:"0 auto",padding:"40px 24px 80px",animation:"fadeUp 0.6s ease both"}}>
<h1 style={{fontFamily:fontD,fontSize:"clamp(24px,4vw,36px)",fontWeight:700,textAlign:"center",marginBottom:8}}>{t.title}</h1>
<p style={{textAlign:"center",color:textS,fontSize:14,marginBottom:32}}>{t.subtitle}</p>
{t.categories.map((cat,ci)=>(<div key={ci} style={{background:bgCard,borderRadius:14,padding:20,border:`1px solid ${border}`,marginBottom:12}}>
<h3 style={{fontFamily:fontD,fontSize:16,fontWeight:600,color:accent,marginBottom:12}}>{catIcons[ci]} {cat.name}</h3>
<div style={{display:"flex",flexWrap:"wrap",gap:8}}>{cat.items.map((item,ii)=>{const key=cat.name+":"+item;const isSel=selected.includes(key);return(<button key={ii} onClick={()=>toggle(cat.name,item)} style={{padding:"8px 14px",borderRadius:20,border:`1px solid ${isSel?gold:border}`,background:isSel?(dark?"rgba(212,175,55,0.15)":"rgba(212,175,55,0.12)"):"transparent",color:isSel?gold:textP,fontSize:12,fontWeight:isSel?600:400,cursor:"pointer",transition:"all 0.2s",fontFamily:fontB}}>{item}</button>)})}</div>
</div>))}
<div style={{background:bgCard,borderRadius:14,padding:20,border:`1px solid ${gold}33`,marginBottom:12}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h3 style={{fontFamily:fontD,fontSize:16,fontWeight:600,color:gold}}>{t.selected} ({selected.length})</h3>{selected.length>0&&<button onClick={()=>setSelected([])} style={{border:"none",cursor:"pointer",background:"transparent",color:textS,fontSize:12}}>{t.clear}</button>}</div>
{selected.length===0?<p style={{fontSize:13,color:textS}}>{t.empty}</p>:<div style={{display:"flex",flexWrap:"wrap",gap:8}}>{selected.map((s,i)=>{const[cat,item]=s.split(":");return(<span key={i} style={{padding:"6px 12px",borderRadius:16,background:`${gold}22`,color:gold,fontSize:12,fontWeight:500,display:"flex",alignItems:"center",gap:6}}>{item}<button onClick={()=>toggle(cat,item)} style={{border:"none",cursor:"pointer",background:"transparent",color:gold,fontSize:14,padding:0}}>×</button></span>)})}</div>}
</div>
<div style={{background:bgCard,borderRadius:14,padding:20,border:`1px solid ${border}`,marginBottom:24}}>
<h3 style={{fontFamily:fontD,fontSize:16,fontWeight:600,color:accent,marginBottom:12}}>{t.tips}</h3>
{t.tipsText.map((tip,i)=>(<div key={i} style={{display:"flex",gap:8,alignItems:"flex-start",marginBottom:8}}><span style={{color:gold,fontSize:14}}>•</span><span style={{fontSize:13,color:textS,lineHeight:1.6}}>{tip}</span></div>))}
</div>
<div style={{background:`linear-gradient(135deg,${dark?"rgba(212,175,55,0.06)":"rgba(212,175,55,0.08)"},transparent)`,borderRadius:14,padding:24,textAlign:"center",border:`1px solid ${gold}22`}}><p style={{fontSize:14,color:textS,marginBottom:12}}>{t.sponsor.text}</p><a href="https://instagram.com/istanbulgumustr" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"10px 28px",borderRadius:8,background:`linear-gradient(135deg,${gold},#c9a227)`,color:"#0f0f14",fontWeight:600,fontSize:14,textDecoration:"none"}}>{t.sponsor.cta}</a></div>
</div></div>);}
