import { useState } from "react";
const T={tr:{title:"Gümüş Zekât Hesaplayıcı",subtitle:"Gümüş nisabı üzerinden zekât miktarınızı hesaplayın",weightLabel:"Sahip Olduğunuz Gümüş (gram)",priceLabel:"Güncel Gümüş Fiyatı (₺/gram)",nisab:"Nisab Miktarı",nisabVal:"595 gram (80,18 miskal)",zakatable:"Zekâta Tabi Miktar",zakatAmount:"Zekât Miktarı (%2,5)",zakatMoney:"Parasal Karşılık",mezhep:"Mezhep Görüşleri",mezheps:[{name:"Hanefi",rule:"Saf gümüş 595g (200 dirhem) nisabı aşarsa, toplam değerin %2,5'i"},{name:"Şafii",rule:"595g nisabı aşan gümüş üzerinden %2,5"},{name:"Maliki",rule:"595g nisabı aşan gümüşte %2,5; ticari amaçlı ise piyasa değeri üzerinden"},{name:"Hanbeli",rule:"595g nisabı aşan gümüş ve gümüş eşya üzerinden %2,5"}],belowNisab:"Gümüş miktarınız nisab miktarının altında. Zekât yükümlülüğü bulunmamaktadır.",note:"Bu hesaplayıcı bilgilendirme amaçlıdır. Kesin fıkhî değerlendirme için yetkili din alimlerine danışınız.",sponsor:{text:"925 ayar gümüş takıları keşfedin.",cta:"İstanbul Gümüş"}},
en:{title:"Silver Zakat Calculator",subtitle:"Calculate your zakat amount based on silver nisab threshold",weightLabel:"Silver You Own (grams)",priceLabel:"Current Silver Price ($/gram)",nisab:"Nisab Threshold",nisabVal:"595 grams (80.18 mithqal)",zakatable:"Zakatable Amount",zakatAmount:"Zakat Amount (2.5%)",zakatMoney:"Monetary Equivalent",mezhep:"School of Thought Views",mezheps:[{name:"Hanafi",rule:"If pure silver exceeds 595g (200 dirham) nisab, 2.5% of total value"},{name:"Shafi'i",rule:"2.5% on silver exceeding 595g nisab"},{name:"Maliki",rule:"2.5% on silver exceeding 595g; market value if commercial"},{name:"Hanbali",rule:"2.5% on silver and silverware exceeding 595g"}],belowNisab:"Your silver amount is below the nisab threshold. No zakat obligation.",note:"This calculator is for informational purposes. Consult qualified scholars for precise rulings.",sponsor:{text:"Discover 925 sterling silver jewelry.",cta:"İstanbul Gümüş"}},
ar:{title:"حاسبة زكاة الفضة",subtitle:"احسب مقدار زكاتك بناءً على نصاب الفضة",weightLabel:"الفضة التي تملكها (غرام)",priceLabel:"سعر الفضة الحالي ($/غرام)",nisab:"مقدار النصاب",nisabVal:"٥٩٥ غرام (٨٠,١٨ مثقال)",zakatable:"المبلغ الخاضع للزكاة",zakatAmount:"مقدار الزكاة (٢,٥٪)",zakatMoney:"المعادل النقدي",mezhep:"آراء المذاهب",mezheps:[{name:"الحنفي",rule:"إذا تجاوزت الفضة النقية ٥٩٥غ (٢٠٠ درهم)، ٢,٥٪ من إجمالي القيمة"},{name:"الشافعي",rule:"٢,٥٪ على الفضة المتجاوزة ٥٩٥غ"},{name:"المالكي",rule:"٢,٥٪ على الفضة المتجاوزة ٥٩٥غ؛ القيمة السوقية إذا كانت تجارية"},{name:"الحنبلي",rule:"٢,٥٪ على الفضة وأواني الفضة المتجاوزة ٥٩٥غ"}],belowNisab:"كمية الفضة لديك أقل من النصاب. لا تجب الزكاة.",note:"هذه الحاسبة لأغراض إعلامية. استشر العلماء المؤهلين.",sponsor:{text:"اكتشف مجوهرات فضة ٩٢٥.",cta:"إسطنبول غوموش"}}
};
const NISAB=595;
export default function ZakatCalculator(){
const[lang,setLang]=useState("tr");const[dark,setDark]=useState(true);const[weight,setWeight]=useState(600);const[price,setPrice]=useState(35);
const t=T[lang];const isRTL=lang==="ar";const aboveNisab=weight>=NISAB;const zakatGram=aboveNisab?weight*0.025:0;const zakatVal=zakatGram*price;
const bgP=dark?"#0f0f14":"#FAFAF5";const textP=dark?"#e8e8ec":"#2C2C2C";const textS=dark?"#9a9aaa":"#6B7280";const accent=dark?"#C0C0C0":"#708090";const gold="#D4AF37";const border=dark?"rgba(192,192,192,0.1)":"rgba(0,0,0,0.06)";const bgCard=dark?"#1a1a24":"#ffffff";const fontD="'Playfair Display',Georgia,serif";const fontB=lang==="ar"?"'Noto Naskh Arabic',serif":"'Source Sans 3',sans-serif";
return(<div dir={isRTL?"rtl":"ltr"} style={{fontFamily:fontB,background:bgP,color:textP,minHeight:"100vh"}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Source+Sans+3:wght@300;400;500;600&family=Noto+Naskh+Arabic:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');*{margin:0;padding:0;box-sizing:border-box}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}input[type=number]{width:100%;padding:12px 16px;border-radius:8px;border:1px solid ${border};background:${bgP};color:${textP};font-size:16px;font-family:'JetBrains Mono',monospace;outline:none}input[type=number]:focus{border-color:${gold}}`}</style>
<nav style={{position:"sticky",top:0,zIndex:100,background:dark?"rgba(15,15,20,0.88)":"rgba(250,250,245,0.88)",backdropFilter:"blur(20px)",borderBottom:`1px solid ${border}`,padding:"0 24px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${accent},${gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:"#0f0f14",fontFamily:fontD}}>Ag</div><span style={{fontFamily:fontD,fontWeight:600,fontSize:16}}>SilverAtlas</span></div><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{display:"flex",gap:2,background:dark?"rgba(255,255,255,0.05)":"rgba(0,0,0,0.04)",borderRadius:7,padding:2}}>{["tr","en","ar"].map(l=>(<button key={l} onClick={()=>setLang(l)} style={{border:"none",cursor:"pointer",padding:"3px 9px",borderRadius:5,fontSize:11,fontWeight:lang===l?600:400,fontFamily:l==="ar"?"'Noto Naskh Arabic',serif":fontB,background:lang===l?(dark?"rgba(192,192,192,0.15)":"rgba(0,0,0,0.08)"):"transparent",color:lang===l?textP:textS}}>{l==="ar"?"عر":l.toUpperCase()}</button>))}</div><button onClick={()=>setDark(!dark)} style={{border:"none",cursor:"pointer",background:"transparent",color:textS,fontSize:16,padding:4}}>{dark?"☀️":"🌙"}</button></div></nav>
<div style={{maxWidth:560,margin:"0 auto",padding:"40px 24px 80px",animation:"fadeUp 0.6s ease both"}}>
<h1 style={{fontFamily:fontD,fontSize:"clamp(24px,4vw,36px)",fontWeight:700,textAlign:"center",marginBottom:8}}>☪️ {t.title}</h1>
<p style={{textAlign:"center",color:textS,fontSize:14,marginBottom:32}}>{t.subtitle}</p>
<div style={{background:bgCard,borderRadius:16,padding:24,border:`1px solid ${border}`,marginBottom:20}}>
<div style={{marginBottom:16}}><label style={{fontSize:13,color:textS,display:"block",marginBottom:6}}>{t.weightLabel}</label><input type="number" value={weight} onChange={e=>setWeight(+e.target.value)} min={0}/></div>
<div style={{marginBottom:16}}><label style={{fontSize:13,color:textS,display:"block",marginBottom:6}}>{t.priceLabel}</label><input type="number" value={price} onChange={e=>setPrice(+e.target.value)} min={0} step={0.01}/></div>
<div style={{padding:16,background:dark?"rgba(192,192,192,0.04)":"rgba(192,192,192,0.06)",borderRadius:10,marginBottom:12}}><div style={{fontSize:12,color:textS,marginBottom:4}}>{t.nisab}</div><div style={{fontSize:16,fontWeight:600,color:accent,fontFamily:"'JetBrains Mono',monospace"}}>{t.nisabVal}</div></div>
{aboveNisab?(<div style={{padding:20,background:dark?"rgba(212,175,55,0.08)":"rgba(212,175,55,0.1)",borderRadius:12,textAlign:"center"}}>
<div style={{fontSize:12,color:textS,marginBottom:4}}>{t.zakatAmount}</div>
<div style={{fontSize:32,fontWeight:700,color:gold,fontFamily:"'JetBrains Mono',monospace"}}>{zakatGram.toFixed(2)}g</div>
<div style={{fontSize:14,color:textS,marginTop:8}}>{t.zakatMoney}: <strong style={{color:gold}}>{zakatVal.toFixed(2)} {lang==="tr"?"₺":"$"}</strong></div>
</div>):(<div style={{padding:16,background:"rgba(76,175,80,0.1)",borderRadius:10,textAlign:"center",fontSize:14,color:"#4CAF50"}}>{t.belowNisab}</div>)}
</div>
<div style={{background:bgCard,borderRadius:16,padding:24,border:`1px solid ${border}`,marginBottom:20}}>
<h3 style={{fontFamily:fontD,fontSize:18,fontWeight:600,color:accent,marginBottom:16}}>{t.mezhep}</h3>
{t.mezheps.map((m,i)=>(<div key={i} style={{padding:"12px 0",borderBottom:i<t.mezheps.length-1?`1px solid ${border}`:"none"}}><div style={{fontSize:14,fontWeight:600,color:textP,marginBottom:4}}>{m.name}</div><div style={{fontSize:13,color:textS,lineHeight:1.6}}>{m.rule}</div></div>))}
</div>
<p style={{fontSize:11,color:textS,textAlign:"center",marginBottom:20}}>{t.note}</p>
<div style={{background:`linear-gradient(135deg,${dark?"rgba(212,175,55,0.06)":"rgba(212,175,55,0.08)"},transparent)`,borderRadius:14,padding:24,textAlign:"center",border:`1px solid ${gold}22`}}><p style={{fontSize:14,color:textS,marginBottom:12}}>{t.sponsor.text}</p><a href="https://instagram.com/istanbulgumustr" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"10px 28px",borderRadius:8,background:`linear-gradient(135deg,${gold},#c9a227)`,color:"#0f0f14",fontWeight:600,fontSize:14,textDecoration:"none"}}>{t.sponsor.cta}</a></div>
</div></div>);}
